apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: default-configuration
spec:
  profile: default
  meshConfig:
    outboundTrafficPolicy:
      mode: REGISTRY_ONLY
    accessLogFile: /dev/stdout
  components:
    egressGateways:
    - name: istio-egressgateway
      enabled: true
    ingressGateways:
    - name: istio-ingressgateway
      k8s:
        hpaSpec:
          maxReplicas: 1
        service:
          type: NodePort
        overlays:
        - apiVersion: v1
          kind: Service
          name: istio-ingressgateway
          patches:
          - path: spec.ports
            value:
            - name: http2
              port: 8080
              targetPort: 8080
              nodePort: 30000
            - name: status-port
              port: 15021
              targetPort: 15021
              nodePort: 30002
            - name: https
              port: 8443
              targetPort: 8443
              nodePort: 30001
        - apiVersion: policy/v1beta1
          kind: PodDisruptionBudget
          name: istio-ingressgateway
          patches:
          - path: spec.minAvailable
            value: 0