apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: default-host
  namespace: default
spec:
  hosts:
  - srv.nl
  gateways:
  - mesh
  http:
  # simple example
  - match:
    - uri:
        prefix: "/v2"
    route:
    - destination:
        host: service-v1
        subset: v1
      weight: 100